server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:watches
    username: sa
    password: sa

  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: create
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialec: org.hibernate.dialect.H2Dialect
